docs: Add a link to solveCaptcha's API
cozy/cozy.github.io pull request #225
Opened 2021-12-03 15:09 UTC by Crash--

2021-12-07 15:02 UTC, sblaisot requested changes

2021-12-08 09:25 UTC, Crash-- commented on src/tutorials/konnector/scrape-data.md
> +- is there a captcha? If yes you can take a look at our [solveCaptcha API](https://docs.cozy.io/en/cozy-konnector-libs/api/#solvecaptcha_1)
I was too lazy to find it. Thanks @sblaisot !

2021-12-09 11:05 UTC, sblaisot approved these changes

2021-12-09 11:06 UTC, sblaisot commented
LGTM, Thanks!

2021-12-09 11:09 UTC, merged